<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>false</SelfContained>
		<OutputType>Library</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="accoremgd">
			<HintPath>..\..\..\AutoCAD 2027\accoremgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="acdbmgd">
			<HintPath>..\..\..\AutoCAD 2027\acdbmgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="acmgd">
			<HintPath>..\..\..\AutoCAD 2027\acmgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.Speech" Version="10.0.11" />
	</ItemGroup>
	<Target Name="CopyWebView2Native" AfterTargets="Build">
		<ItemGroup>
			<WebView2NativeFiles Include="$(OutputPath)runtimes\win-x64\native\*.dll" />
		</ItemGroup>
		<Copy SourceFiles="@(WebView2NativeFiles)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
	</Target>

</Project>